version: "3.9"

services:
  app:
    image: your_dockefile  # Substitua pela imagem real da sua aplicação
    container_name: app
    ports:
      - "8000:3000"               # Altere para a porta que seu app utiliza
    depends_on:
      - postgresql
      - postgresql2
      - minio
    environment:
      DB1_HOST: postgresql
      DB2_HOST: postgresql2
      MINIO_URL: http://minio:9000

  ssp_criminosos:
    image: pgvector/pgvector:pg17
    container_name: criminosos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: ssp_criminosos
    ports:
      - "5432:5432"
    volumes:
      - pgdata_criminosos:/var/lib/postgresql/data

  ssp_usuarios:
    image: postgres:17
    container_name: usuarios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: ssp_usuario
    ports:
      - "5433:5432"  # Evita conflito de porta com o primeiro PostgreSQL
    volumes:
      - pgdata_usuarios:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # Console web do MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  pgdata_usuarios:
  pgdata_criminosos:
  minio-data:
